name: Terraform

on:
  push:
    branches:
      - main

concurrency:
  group: terraform-${{ github.ref }}
  cancel-in-progress: false

jobs:
  terraform:
    name: "Infra"
    runs-on: ubuntu-latest

    env:
      TF_VAR_gemini_key: ${{ secrets.GEMINI_API_KEY }}
      TF_VAR_telegram_key: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TF_VAR_vault_api_url: ${{ secrets.VAULT_API_URL }}
      TF_VAR_her_api_url: ${{ secrets.HER_API_URL }}
      TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
      TF_VAR_region: ${{ secrets.GCP_REGION }}
      TF_VAR_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
      TF_VAR_google_api_key: ${{ secrets.GOOGLE_API_KEY }}
      TF_VAR_memory_dump_seconds: ${{ secrets.MEMORY_DUMP_SECONDS }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform init

      - name: Validate Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform validate

      - name: Refresh Terraform State
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform apply -refresh-only -auto-approve

      - name: Plan Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: terraform plan -out=tfplan

      - name: Apply Terraform (Manual Approval)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}